In [ ]:
%run ETL.ipynb

## SQL Queries

### 1. NÃºmero de rutas por pais

In [13]:
query1 = """
    select t2.pais_aeropuerto, count(t1.cod_aeropuerto_ori) as num_rutas from
    (
        select cod_aeropuerto_ori
        from HC_RUTAS

    ) t1 join 
    (
        select cod_aeropuerto, pais_aeropuerto from DM_AEROPUERTOS AS t2
    ) t2 on cod_aeropuerto_ori=cod_aeropuerto
    group by pais_aeropuerto
    order by num_rutas desc, cod_aeropuerto_ori
    """

In [26]:
%sql $query1

 * mysql+pymysql://uvzyojikw6equtfk:***@b4xagkgex6krc881bjyk-mysql.services.clever-cloud.com/b4xagkgex6krc881bjyk
227 rows affected.

[('United States', 13193),
 ('China', 8197),
 ('United Kingdom', 2662),
 ('Spain', 2531),
 ('Germany', 2353),
 ('Canada', 1847),
 ('France', 1846),
 ('Russia', 1831),
 ('Italy', 1776),
 ('India', 1507),
 ('Brazil', 1395),
 ('Japan', 1295),
 ('Australia', 1111),
 ('Mexico', 1060),
 ('Turkey', 977),
 ('Indonesia', 833),
 ('Greece', 787),
 ('United Arab Emirates', 752),
 ('Norway', 648),
 ('Thailand', 605),
 ('South Korea', 589),
 ('Netherlands', 570),
 ('Malaysia', 567),
 ('Saudi Arabia', 550),
 ('Portugal', 530),
 ('Switzerland', 524),
 ('Sweden', 474),
 ('Iran', 431),
 ('Taiwan', 414),
 ('Belgium', 412),
 ('Singapore', 408),
 ('Philippines', 394),
 ('Austria', 388),
 ('Poland', 363),
 ('Colombia', 361),
 ('Hong Kong', 355),
 ('Morocco', 310),
 ('Denmark', 309),
 ('Egypt', 307),
 ('Ireland', 295),
 ('Vietnam', 289),
 ('Pakistan', 282),
 ('South Africa', 268),
 ('Argentina', 255),
 ('Desconocido', 239),
 ('Finland', 219),
 ('Algeria', 218),
 ('New Zealand', 218),
 ('Ukraine', 213),
 ('Kazakhstan', 208),
 ('Croatia', 204),
 ('Kenya', 201),
 ('Tunisia', 200),
 ('Czech Republic', 192),
 ('Venezuela', 192),
 ('Qatar', 189),
 ('Peru', 180),
 ('Romania', 178),
 ('Papua New Guinea', 167),
 ('Dominican Republic', 164),
 ('Chile', 156),
 ('Cyprus', 149),
 ('Israel', 147),
 ('Bahamas', 143),
 ('Uzbekistan', 141),
 ('Ethiopia', 131),
 ('Panama', 131),
 ('Costa Rica', 130),
 ('Nigeria', 122),
 ('Kuwait', 120),
 ('Puerto Rico', 116),
 ('Sri Lanka', 115),
 ('Malta', 113),
 ('Jordan', 113),
 ('Oman', 112),
 ('French Polynesia', 109),
 ('Serbia', 107),
 ('Myanmar', 104),
 ('Bangladesh', 104),
 ('Netherlands Antilles', 101),
 ('Latvia', 101),
 ('Libya', 100),
 ('Hungary', 100),
 ('Bolivia', 100),
 ('Cuba', 96),
 ('Vanuatu', 96),
 ('Ecuador', 96),
 ('Yemen', 93),
 ('Tajikistan', 92),
 ('Bulgaria', 89),
 ('Greenland', 89),
 ('Bahrain', 84),
 ('Lithuania', 80),
 ('Macao', 79),
 ('Angola', 78),
 ('Belize', 78),
 ('Kyrgyzstan', 76),
 ('Tanzania', 75),
 ('Jamaica', 75),
 ('Iraq', 73),
 ('Cameroon', 72),
 ('Azerbaijan', 72),
 ('Cambodia', 72),
 ('Luxembourg', 70),
 ('Senegal', 70),
 ('Fiji', 69),
 ('Madagascar', 67),
 ('Honduras', 67),
 ('Lebanon', 67),
 ('Ghana', 64),
 ('Mozambique', 61),
 ('Congo (Kinshasa)', 61),
 ('Solomon Islands', 59),
 ('Cape Verde', 58),
 ('Zambia', 55),
 ('Maldives', 55),
 ('Belarus', 54),
 ('Iceland', 53),
 ('El Salvador', 53),
 ('Sudan', 52),
 ('Nepal', 52),
 ("Cote d'Ivoire", 50),
 ('Laos', 49),
 ('Georgia', 48),
 ('Armenia', 46),
 ('US Virgin Islands', 44),
 ('Aruba', 44),
 ('Congo (Brazzaville)', 43),
 ('Afghanistan', 43),
 ('Mauritius', 42),
 ('Benin', 41),
 ('Estonia', 41),
 ('Rwanda', 41),
 ('Guatemala', 40),
 ('Trinidad and Tobago', 39),
 ('Jersey', 38),
 ('Turks and Caicos Islands', 38),
 ('Zimbabwe', 37),
 ('Uganda', 36),
 ('Albania', 36),
 ('New Caledonia', 36),
 ('Burkina Faso', 35),
 ('Guam', 35),
 ('Antigua and Barbuda', 35),
 ('Moldova', 34),
 ('Slovenia', 33),
 ('Guadeloupe', 33),
 ('Mongolia', 33),
 ('Namibia', 32),
 ('Somalia', 32),
 ('Saint Lucia', 30),
 ('Cayman Islands', 29),
 ('Mali', 28),
 ('Montenegro', 27),
 ('Haiti', 27),
 ('Slovakia', 26),
 ('Uruguay', 26),
 ('Gabon', 25),
 ('Macedonia', 24),
 ('Barbados', 23),
 ('Martinique', 23),
 ('Brunei', 23),
 ('Djibouti', 23),
 ('Botswana', 22),
 ('Reunion', 22),
 ('Sierra Leone', 22),
 ('Paraguay', 22),
 ('Cook Islands', 21),
 ('Togo', 20),
 ('Guernsey', 20),
 ('Bosnia and Herzegovina', 20),
 ('Saint Kitts and Nevis', 19),
 ('Liberia', 18),
 ('Guinea', 18),
 ('Niger', 17),
 ('Malawi', 17),
 ('Dominica', 17),
 ('Equatorial Guinea', 16),
 ('Mauritania', 16),
 ('British Virgin Islands', 16),
 ('Mayotte', 15),
 ('Nicaragua', 15),
 ('Turkmenistan', 15),
 ('Bermuda', 15),
 ('Seychelles', 14),
 ('Grenada', 14),
 ('Gambia', 13),
 ('Burundi', 13),
 ('South Sudan', 12),
 ('Northern Mariana Islands', 12),
 ('Isle of Man', 11),
 ('Comoros', 10),
 ('Palau', 10),
 ('Suriname', 10),
 ('Chad', 9),
 ('Micronesia', 9),
 ('Guyana', 9),
 ('Eritrea', 8),
 ('Marshall Islands', 7),
 ('Kiribati', 7),
 ('French Guiana', 7),
 ('Guinea-Bissau', 7),
 ('Western Sahara', 7),
 ('Gibraltar', 6),
 ('Anguilla', 6),
 ('Tonga', 5),
 ('Samoa', 5),
 ('Bhutan', 5),
 ('North Korea', 5),
 ('Faroe Islands', 4),
 ('Saint Vincent and the Grenadines', 4),
 ('East Timor', 4),
 ('Wallis and Futuna', 4),
 ('Central African Republic', 3),
 ('Sao Tome and Principe', 3),
 ('Saint Pierre and Miquelon', 3),
 ('Norfolk Island', 3),
 ('Nauru', 3),
 ('Christmas Island', 2),
 ('Falkland Islands (Malvinas)', 1),
 ('Swaziland', 1),
 ('Lesotho', 1),
 ('American Samoa', 1),
 ('Tuvalu', 1),
 ('Monaco', 1),
 ('Niue', 1),
 ('Cocos (Keeling) Islands', 1)]

### 2. NÃºmero de rutas de cada paÃ­s, como paÃ­s de la aerolÃ­nea ordenadas de forma que salga el primero el paÃ­s con mÃ¡s rutas. Mostrar el nombre del paÃ­s.

In [15]:
query2 = """
    select t2.pais_aerolinea, count(t1.cod_aerolinea) as num_rutas from
    (
        select cod_aerolinea from HC_RUTAS
    ) as t1 join 
    (
        select cod_aerolinea, nombre_aerolinea, pais_aerolinea from DM_AEROLINEAS AS t2
    ) as t2 on t2.COD_AEROLINEA=t1.cod_aerolinea
    group by pais_aerolinea 
    order by num_rutas desc, pais_aerolinea
"""

In [16]:
%sql $query2

 * mysql+pymysql://uvzyojikw6equtfk:***@b4xagkgex6krc881bjyk-mysql.services.clever-cloud.com/b4xagkgex6krc881bjyk
167 rows affected.

[('United States', 12785),
 ('China', 7262),
 ('United Kingdom', 3336),
 ('Germany', 2942),
 ('Ireland', 2760),
 ('France', 2044),
 ('Russia', 1830),
 ('Canada', 1662),
 ('India', 1441),
 ('Japan', 1373),
 ('Italy', 1300),
 ('Netherlands', 1151),
 ('Turkey', 1142),
 ('Australia', 1092),
 ('Spain', 1064),
 ('Brazil', 1052),
 ('United Arab Emirates', 977),
 ('Taiwan', 880),
 ('Mexico', 808),
 ('Norway', 786),
 ('Indonesia', 768),
 (None, 679),
 ('Malaysia', 642),
 ('Sweden', 634),
 ('Republic of Korea', 615),
 ('ALASKA', 530),
 ('Saudi Arabia', 493),
 ('Hungary', 463),
 ('Singapore', 447),
 ('Philippines', 430),
 ('Thailand', 428),
 ('Austria', 425),
 ('Portugal', 417),
 ('Iran', 416),
 ('Greece', 392),
 ('Switzerland', 388),
 ('Chile', 338),
 ('Ethiopia', 337),
 ('Pakistan', 336),
 ('Burundi', 332),
 ('Finland', 328),
 ('Egypt', 297),
 ('AVIANCA', 286),
 ('Morocco', 284),
 ('Hong Kong SAR of China', 282),
 ('Qatar', 278),
 ('South Africa', 262),
 ('Argentina', 256),
 ('Algeria', 234),
 ('New Zealand', 233),
 ('Belgium', 232),
 ('Vietnam', 229),
 ('Kazakhstan', 223),
 ('Tunisia', 211),
 ('Reunion', 210),
 ('Kenya', 199),
 ('Panama', 184),
 ('Papua New Guinea', 179),
 ('Czech Republic', 178),
 ('Ukraine', 175),
 ('Senegal', 168),
 ('Poland', 156),
 ('Ecuador', 154),
 ('Uzbekistan', 151),
 ('Israel', 147),
 ('Denmark', 142),
 ('Jordan', 131),
 ('Bangladesh', 124),
 ('Peru', 120),
 ('Libya', 118),
 ('Latvia', 114),
 ('Croatia', 112),
 ('Venezuela', 112),
 ('Luxembourg', 110),
 ('Kuwait', 109),
 ('Sri Lanka', 107),
 ('Oman', 98),
 ('Romania', 98),
 ('French Polynesia', 97),
 ('DRAGON', 96),
 ('Yemen', 96),
 ('Colombia', 95),
 ('Georgia', 92),
 ('Vanuatu', 92),
 ('Malta', 84),
 ('Nigeria', 84),
 ('Belarus', 82),
 ('Fiji', 78),
 ('Bahrain', 77),
 ('Serbia', 77),
 ('Iceland', 76),
 ('Madagascar', 75),
 ('Mozambique', 74),
 ('Angola', 71),
 ('Netherlands Antilles', 70),
 ('South Korea', 70),
 ('Cambodia', 68),
 ('Lebanon', 65),
 ('Trinidad and Tobago', 64),
 ('Antigua and Barbuda', 62),
 ('Solomon Islands', 60),
 ('Cuba', 59),
 ('Bahamas', 58),
 ('Bulgaria', 56),
 ('Macao', 56),
 ('Azerbaijan', 54),
 ('Mauritius', 51),
 ('Lao Peoples Democratic Republic', 48),
 ('Afghanistan', 41),
 ('American Samoa', 41),
 ('Rwanda', 40),
 ('Slovenia', 40),
 ('Bolivia', 39),
 ('Tanzania', 39),
 ('Costa Rica', 38),
 ('Moldova', 38),
 ('Belize', 35),
 ('Namibia', 35),
 ('Burma', 34),
 ('Sudan', 34),
 ('Tajikistan', 34),
 ('Cyprus', 31),
 ('Nepal', 31),
 ('Brunei', 30),
 ('Maldives', 30),
 ('Mauritania', 30),
 ('Cameroon', 29),
 ('Myanmar', 29),
 ('Estonia', 26),
 ('Montenegro', 26),
 ('Zambia', 26),
 ('Botswana', 24),
 ('Guadeloupe', 24),
 ('Niger', 24),
 ('Zimbabwe', 24),
 ('Cayman Islands', 23),
 ('Burkina Faso', 22),
 ('Comoros', 22),
 ('Lithuania', 21),
 ('Armenia', 20),
 ('Bhutan', 20),
 ('Mongolia', 20),
 ('Suriname', 20),
 ('Paraguay', 18),
 ('Uruguay', 18),
 ('Eritrea', 16),
 ('Turkmenistan', 16),
 ('Cook Islands', 13),
 ('Sierra Leone', 12),
 ('Bosnia and Herzegovina', 10),
 ('Canadian Territories', 10),
 ('Seychelles', 10),
 ('Faroe Islands', 9),
 ("Democratic People's Republic of Korea", 8),
 ('Ghana', 8),
 ('Nauru', 8),
 ('Russian Federation', 8),
 ('Aruba', 6),
 ('British Virgin Islands', 6),
 ('Djibouti', 6),
 ('Uganda', 6),
 ('Albania', 4),
 ('Benin', 4),
 ('Congo (Kinshasa)', 4),
 ('Republic of the Congo', 4),
 ('Gabon', 2),
 ('Kyrgyzstan', 2)]

### 3. NÃºmero de rutas de cada equipamiento ordenadas de forma que salga el primero el equipamiento con mÃ¡s rutas. Mostrar el nombre del equipamiento. Mostrar solo los equipamientos con mÃ¡s de 2000 rutas.

In [17]:
query3="""
select t2.desc_equipamiento, t1.num_rutas from 
(
    select cod_equipamiento, count(cod_equipamiento) as num_rutas 
    from CO_RUTAS_EQUIPAMIENTOS
    group by cod_equipamiento
) t1 join
(
    select cod_equipamiento, desc_equipamiento from DM_EQUIPAMIENTOS
) t2 on t2.cod_equipamiento=t1.cod_equipamiento
where num_rutas > 2000
order by num_rutas desc, desc_equipamiento
"""

In [18]:
%sql $query3

 * mysql+pymysql://uvzyojikw6equtfk:***@b4xagkgex6krc881bjyk-mysql.services.clever-cloud.com/b4xagkgex6krc881bjyk
8 rows affected.

[('Airbus A320-100/200                           ', 15184),
 ('Boeing 737-800 pax                            ', 10183),
 ('Airbus A319                                   ', 7535),
 ('Airbus A321-100/200                           ', 3512),
 ('Boeing 737-800 (winglets) pax                 ', 3223),
 ('Boeing 737 all pax models                     ', 2759),
 ('Boeing 737-700 (winglets) pax                 ', 2446),
 ('Canadair Regional Jet                         ', 2180)]

### 4. NÃºmero de rutas por equipamiento para las rutas cuyo aeropuerto origen es Barajas (1229) ordenadas de forma que salga el primero el equipamiento con mÃ¡s rutas. Mostrar el nombre del equipamiento.

In [19]:
query4 = """
select t3.desc_equipamiento, count(t2.cod_ruta) as num_rutas from
(
    select cod_ruta, cod_equipamiento
    from CO_RUTAS_EQUIPAMIENTOS
) t1 inner join
(
    select cod_ruta, cod_aeropuerto_ori from HC_RUTAS where cod_aeropuerto_ori = 1229
) t2 on t1.cod_ruta=t2.cod_ruta join
(
    select cod_equipamiento, desc_equipamiento from DM_EQUIPAMIENTOS
) t3 on t1.cod_equipamiento=t3.cod_equipamiento
group by desc_equipamiento
order by num_rutas desc
"""

In [20]:
%sql $query4

 * mysql+pymysql://uvzyojikw6equtfk:***@b4xagkgex6krc881bjyk-mysql.services.clever-cloud.com/b4xagkgex6krc881bjyk
45 rows affected.

[('Boeing 737-800 pax                            ', 62),
 ('Airbus A320-100/200                           ', 61),
 ('Airbus A319                                   ', 55),
 ('Airbus A321-100/200                           ', 29),
 ('Airbus A330-300                               ', 27),
 ('Airbus A318/319/320/321                       ', 20),
 ('Airbus A340-600                               ', 20),
 ('Embraer 190                                   ', 19),
 ('Airbus A330-200                               ', 18),
 ('Canadair Regional Jet 1000                    ', 18),
 ('Canadair Regional Jet 900                     ', 14),
 ('Airbus A330 all models                        ', 13),
 ('Canadair Regional Jet 200                     ', 11),
 ('Airbus A340-500                               ', 10),
 ('Boeing 777 all pax models                     ', 9),
 ('Embraer RJ145 Amazon                          ', 9),
 ('Airbus A340-200                               ', 9),
 ('Airbus A320                                   ', 7),
 ('Boeing 767-300 pax                            ', 6),
 ('Boeing 767-400 pax                            ', 6),
 ('Aerospatiale/Alenia ATR 72                    ', 5),
 ('Aerospatiale/Alenia ATR 42/ ATR 72            ', 5),
 ('Boeing 737 all pax models                     ', 4),
 ('Boeing 747-400 pax                            ', 4),
 ('Boeing 757 all pax models                     ', 4),
 ('Boeing 737-800 (winglets) pax                 ', 4),
 ('Boeing 777-300ER pax                          ', 4),
 ('Airbus A340 all models                        ', 4),
 ('Airbus A340-300                               ', 4),
 ('Boeing 737-700 (winglets) pax                 ', 3),
 ('Boeing 737-700 pax                            ', 3),
 ('Boeing 787-8                                  ', 3),
 ('Boeing 767 all pax models                     ', 2),
 ('Fokker 100                                    ', 2),
 ('Boeing 737-900 pax                            ', 2),
 ('Boeing 757-200 pax                            ', 2),
 ('Boeing 767-200 pax                            ', 2),
 ('Canadair Regional Jet                         ', 2),
 ('Ilyushin IL96 pax                             ', 2),
 ('Airbus A318 ', 1),
 ('Boeing 737-600 pax                            ', 1),
 ('Boeing 737-400 pax                            ', 1),
 ('Embraer 195                                   ', 1),
 ('Avro RJ100 Avroliner                          ', 1),
 ('Boeing 777-200 pax                            ', 1)]

### 5.  Los dos paÃ­ses entre los que hay mÃ¡s rutas.

In [21]:
query5 = """
SELECT t2.pais_aeropuerto AS Origen, t3.pais_aeropuerto AS Destino, COUNT(*) AS num_rutas FROM
(
    SELECT cod_aeropuerto_ori,cod_aeropuerto_des FROM HC_RUTAS
) t1 
JOIN 
(
    SELECT cod_aeropuerto, pais_aeropuerto FROM DM_AEROPUERTOS
) t2 ON t1.cod_aeropuerto_ori=t2.cod_aeropuerto
JOIN
(
   SELECT cod_aeropuerto, pais_aeropuerto FROM DM_AEROPUERTOS
) t3 ON t1.cod_aeropuerto_des=t3.cod_aeropuerto 
WHERE t2.pais_aeropuerto != t3.pais_aeropuerto
GROUP BY Origen,Destino
ORDER BY num_rutas desc
LIMIT 1
"""

In [22]:
%sql $query5

 * mysql+pymysql://uvzyojikw6equtfk:***@b4xagkgex6krc881bjyk-mysql.services.clever-cloud.com/b4xagkgex6krc881bjyk
1 rows affected.

[('United Kingdom', 'Spain', 518)]